/*
public class ExceptionHandling {
	 public static void main(String[] args) {

		    try {
		      int divideByZero = 5 / 0;
		      System.out.println("Rest of code in try block");
		    }

		    catch (ArithmeticException e) {
		      System.out.println("ArithmeticException => " + e.getMessage());
		    }
		  }
}

*/

/*
class ExceptionHandling {

  public static void main(String[] args) {
    try {
      int divideByZero = 5 / 0;
    }

    finally {
      System.out.println("Finally block is always executed");
    }
  }
}

*/
/*    // throw

class ExceptionHandling {
  public static void divideByZero() {
    throw new ArithmeticException("Trying to divide by 0");
  }

  public static void main(String[] args) {
    divideByZero();
  }
}

*/
//trows

/*
 * import java.io.*; class ExceptionHandling{ public static void main(String[]
 * args) throws IOException{ FileWriter file = new FileWriter("d:\\File.txt");
 * file.write("Write Something Here"); file.close(); } }
 */  
 


